services:
#  cake_shop:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: cake_shop
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"