# Logging configuration
logging:
  level:
    org:
      springframework:
        security: TRACE

spring:
  application:
    name: "Cake Shop"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  #  Database configuration
  #  For PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/cake_shop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  #  For H2
  # datasource:
  #   url: "jdbc:h2:mem:testDB"
  #   username: "sa"
  #   password: ""
  #   driver-class-name: org.h2.Driver
  # h2:
  #   console:
  #     enabled: true

  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
  #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        format_sql: true
  #        use_sql_comments: true
        jdbc:
          time_zone: GMT+7
    defer-datasource-initialization: true
  sql:
    init:
      data-locations: classpath:/data.sql
      mode: always

